version: "3.9"

services:
  db_host:
    container_name: db_app
    image: mysql/mysql-server:8.0
    env_file:
      - ./.env
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
    ports:
      - 3333:3306
    volumes:
      - app_data:/var/lib/mysql
    networks:
      - net_app
  api_host:
    container_name: api_blog
    build: .
    command: uvicorn app:app --reload
    volumes:
      - ./api:/api
    # env_file:
    #   - ./.env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 8000:8000
    networks:
      - net_app

volumes:
  app_data:

networks:
  net_app:
